defaults:
  - process: predict
  - dataset: default
  - infer: fp_default
  - hydra: default
  - _self_

model_artifact_dir: "runs/train/fp/lgbm_morgan_desc_v1"

process:
  backend: "fp"

output:
  exp_name: "fp_predict"
