defaults:
  - process: predict
  - dataset: fixture
  - infer: fp_quick
  - hydra: default
  - _self_

model_artifact_dir: "runs/train/fp/fixture_fp_rf"

process:
  backend: "fp"

experiment:
  name: "fixture_fp_predict"

output:
  exp_name: "fixture_fp_predict"
