defaults:
  - process: visualize
  - hydra: default
  - _self_

input:
  evaluate_run_dir: "runs/evaluate/fp_evaluate_quick"

plots:
  splits: ["val", "test"]
  include_train_hist: true

process:
  backend: "fp"

experiment:
  name: "fp_visualize_quick"

output:
  exp_name: "fp_visualize_quick"
