defaults:
  - process: visualize
  - hydra: default
  - _self_

input:
  evaluate_run_dir: "runs/evaluate/fixture_fp_evaluate"

plots:
  splits: ["val", "test"]
  include_train_hist: true

process:
  backend: "fp"

experiment:
  name: "fixture_fp_visualize"

output:
  exp_name: "fixture_fp_visualize"
