defaults:
  - process: evaluate
  - dataset: default
  - task: lj_epsilon
  - eval: default
  - hydra: default
  - _self_

model_artifact_dir: "runs/train/gnn/mpnn_desc_v1"

process:
  backend: "gnn"

experiment:
  name: "gnn_evaluate"

output:
  exp_name: "gnn_evaluate"
