defaults:
  - process: audit_dataset
  - dataset: default
  - task: lj_epsilon
  - audit: default
  - hydra: default
  - _self_

experiment:
  name: "audit_dataset"

output:
  exp_name: "audit_dataset"
